version: '3.9'

services:
  devtimeseries:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/code/api #Aquí, ./api se refiere al directorio en tu máquina local que contiene el código de tu aplicación, mientras que /code/api es la ruta del directorio en el contenedor donde se montará el volumen.
      - ./src:/code/src  # Agregar esta línea para mapear el directorio actual en el contenedor
      - ./data:/code/data
      - ./models:/code/models
      - ./folder_structure.txt:/code/folder_structure.txt # agregar esta línea para mapear el archivo en el contenedor

    environment:
      PYTHONPATH: /code

  jupyter:
    build:
      context: .
      dockerfile: DockerFile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./src:/code/src
      - ./data:/code/data

  # prodtimeseries:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - .:/api
