FROM python:3.11.3-slim-buster

WORKDIR /code

COPY  ./requirements.txt /code/requirements.txt

RUN apt-get update && \
    apt-get install -y locales && \
    sed -i -e 's/# es_CO.UTF-8 UTF-8/es_CO.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

ENV LC_ALL es_CO.UTF-8
ENV LANG es_CO.UTF-8
ENV LANGUAGE es_CO.UTF-8

COPY ./api /code/api

COPY ./src /code/src

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]